(function(){
  "use strict";
  const atlas=window.AESTHETIC_ATLAS;
  const page=document.body.dataset.atlasPage||"home";
  const $=selector=>document.querySelector(selector);
  const esc=value=>String(value==null?"":value).replace(/[&<>\"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[char]));
  const state={query:"",source:"all",tag:"all"};
  const chapter=atlas.chapters.find(item=>item.id===page);
  const number=value=>String(value).padStart(2,"0");

  function shell(){
    document.body.insertAdjacentHTML("afterbegin",`<header class="atlas-topbar"><a class="atlas-brand" href="./design-library.html"><span class="atlas-mark">A</span><span><b>界面审美图鉴</b><span>INTERFACE AESTHETIC ATLAS</span></span></a><nav class="atlas-nav">${atlas.chapters.map(item=>`<a class="${page===item.id?"active":""}" href="./${item.file}">${item.name}</a>`).join("")}<a class="return" href="./app.html">返回项目</a></nav></header>`);
    document.body.insertAdjacentHTML("beforeend",`<div id="atlasBackdrop" class="atlas-modal-backdrop"></div><aside id="atlasModal" class="atlas-modal" aria-hidden="true"><header class="atlas-modal-head"><div><span class="atlas-kicker">ELEMENT / TYPE / EFFECT</span><h2 id="atlasModalTitle"></h2></div><button id="atlasModalClose" class="atlas-modal-close" aria-label="关闭">×</button></header><div id="atlasModalBody" class="atlas-modal-body"></div></aside>`);
  }
  function home(){
    const totalVariants=atlas.elements.reduce((sum,item)=>sum+item.variants.length,0);
    $("#atlasRoot").innerHTML=`<main class="atlas-main"><section class="atlas-home-hero"><span class="atlas-kicker">A GENERAL-PURPOSE DESIGN MEMORY</span><h1>先选审美语言，再组合界面。</h1><p>这不是某个项目的组件库，而是一套可浏览、可比较、可复制的通用界面审美沉淀。每个最小子元素都并列展示三种呈现类型，让选择发生在真正的视觉差异上。</p><div class="atlas-home-stats"><div class="atlas-home-stat"><b>${atlas.elements.length}</b><span>最小子元素</span></div><div class="atlas-home-stat"><b>${totalVariants}</b><span>呈现类型</span></div><div class="atlas-home-stat"><b>${atlas.sources.length}</b><span>参考产品</span></div><div class="atlas-home-stat"><b>${atlas.chapters.length}</b><span>浏览页面</span></div></div></section><section class="chapter-grid">${atlas.chapters.map((item,index)=>{const elements=atlas.elements.filter(element=>element.chapter===item.id);const variants=elements.reduce((sum,element)=>sum+element.variants.length,0);return `<a class="chapter-card" href="./${item.file}"><i>${number(index+1)}</i><h2>${item.name}</h2><p>${item.description}</p><footer><span>${elements.length} ELEMENTS</span><span>${variants} TYPES →</span></footer></a>`}).join("")}</section><section class="source-spectrum"><h2>参考审美光谱</h2><div class="source-cloud">${atlas.sources.map(source=>`<span>${source} · ${atlas.sourceMap[source].length} elements</span>`).join("")}</div></section></main>`
  }
  function chapterPage(){
    const pageElements=atlas.elements.filter(element=>element.chapter===page);
    const tags=[...new Set(pageElements.flatMap(element=>element.tags))].sort();
    $("#atlasRoot").innerHTML=`<main class="atlas-main"><section class="atlas-page-head"><div class="atlas-intro"><span class="atlas-kicker">CHAPTER · ${number(atlas.chapters.findIndex(item=>item.id===page)+1)}</span><h1>${chapter.name}</h1><p>${chapter.description} 左侧是子元素与审美作用，右侧是可以直接比较的呈现类型。</p><div class="atlas-formula"><div><b>子元素</b><span>它在界面中解决什么</span></div><i></i><div><b>呈现类型</b><span>同一元素的不同审美答案</span></div><i></i><div><b>效果与代码</b><span>放大查看并复制使用</span></div></div></div><aside class="atlas-index"><h2>全册目录</h2><p>分为五个页面，保持浏览空间大而清楚。</p><div class="atlas-index-list">${atlas.chapters.map((item,index)=>{const count=atlas.elements.filter(element=>element.chapter===item.id).length;return `<a class="${item.id===page?"active":""}" href="./${item.file}"><i>${number(index+1)}</i><b>${item.name}</b><span>${count} ELEMENTS</span></a>`}).join("")}</div></aside></section><section class="atlas-tools"><label class="atlas-search"><input id="atlasSearch" placeholder="搜索子元素、呈现类型或来源产品"></label><select id="atlasSource"><option value="all">全部参考产品</option>${atlas.sources.map(source=>`<option value="${source}">${source}</option>`).join("")}</select><select id="atlasTag"><option value="all">全部审美标签</option>${tags.map(tag=>`<option value="${tag}">${tag}</option>`).join("")}</select><div id="atlasCount" class="atlas-count">${pageElements.length} ELEMENTS</div></section><section id="elementStack" class="element-stack"></section></main>`;
    $("#atlasSearch").addEventListener("input",event=>{state.query=event.target.value.trim().toLowerCase();renderRows()});
    $("#atlasSource").addEventListener("change",event=>{state.source=event.target.value;renderRows()});
    $("#atlasTag").addEventListener("change",event=>{state.tag=event.target.value;renderRows()});
    renderRows();
  }
  function filtered(){return atlas.elements.filter(element=>element.chapter===page).filter(element=>{
    const hay=[element.id,element.name,element.description,...element.tags,...element.variants.flatMap(variant=>[variant.name,variant.source,variant.description])].join(" ").toLowerCase();
    return (!state.query||hay.includes(state.query))&&(state.source==="all"||element.variants.some(variant=>variant.source===state.source))&&(state.tag==="all"||element.tags.includes(state.tag));
  })}
  function renderRows(){const items=filtered();$("#atlasCount").textContent=`${items.length} ELEMENTS`;$("#elementStack").innerHTML=items.length?items.map((element,index)=>`<article class="element-row"><header class="element-label"><span class="element-number">ELEMENT ${number(index+1)} · ${element.id}</span><h2>${element.name}</h2><p>${element.description}</p><div class="element-tags">${element.tags.map(tag=>`<span>${tag}</span>`).join("")}</div></header><div class="variant-grid">${element.variants.map(variant=>`<section class="variant"><header class="variant-head"><div><b>${variant.name}</b><span>${variant.source}</span></div><code class="variant-code">${variant.id}</code></header><div class="variant-preview aa-demo">${variant.html}</div><footer class="variant-foot"><span>${variant.description}</span><button data-element="${element.id}" data-variant="${variant.id}">放大选择 ↗</button></footer></section>`).join("")}</div></article>`).join(""):`<div class="atlas-empty">没有匹配的子元素，请尝试减少筛选条件。</div>`;activateDemos($("#elementStack"))}
  function openModal(elementId,variantId){const element=atlas.elements.find(item=>item.id===elementId),variant=element&&element.variants.find(item=>item.id===variantId);if(!variant)return;$("#atlasModalTitle").textContent=`${element.name} · ${variant.name}`;$("#atlasModalBody").innerHTML=`<div class="atlas-modal-preview aa-demo">${variant.html}</div><div class="atlas-modal-meta"><div><b>审美作用</b><span>${element.description}</span></div><div><b>呈现类型</b><span>${variant.description}</span></div><div><b>参考产品</b><span>${variant.source}</span></div><div><b>类型 ID</b><span>${variant.id}</span></div></div><div class="atlas-code-head"><b>可复制 HTML</b><button class="atlas-copy" data-copy="${element.id}" data-variant="${variant.id}">复制代码</button></div><pre class="atlas-code"><code>${esc(variant.html)}</code></pre>`;activateDemos($("#atlasModalBody"));$("#atlasBackdrop").classList.add("open");$("#atlasModal").classList.add("open");$("#atlasModal").setAttribute("aria-hidden","false")}
  function closeModal(){$("#atlasBackdrop").classList.remove("open");$("#atlasModal").classList.remove("open");$("#atlasModal").setAttribute("aria-hidden","true")}
  async function copy(button){const element=atlas.elements.find(item=>item.id===button.dataset.copy),variant=element&&element.variants.find(item=>item.id===button.dataset.variant);if(!variant)return;try{await navigator.clipboard.writeText(variant.html);button.textContent="已复制";setTimeout(()=>button.textContent="复制代码",1000)}catch(error){button.textContent="复制失败"}}
  function interactions(event){const toggle=event.target.closest('[data-aa="switch"]');if(toggle)toggle.classList.toggle("on");const chip=event.target.closest('[data-aa="chip"]');if(chip)chip.classList.toggle("active");const accordion=event.target.closest('[data-aa="accordion"] button');if(accordion)accordion.parentElement.classList.toggle("open")}
  function activateDemos(root){root.querySelectorAll('[data-aa="accordion"]').forEach(item=>item.classList.remove("open"))}
  shell();if(page==="home")home();else chapterPage();
  document.addEventListener("click",event=>{const inspect=event.target.closest("[data-element][data-variant]:not([data-copy])");if(inspect)openModal(inspect.dataset.element,inspect.dataset.variant);const copyButton=event.target.closest("[data-copy]");if(copyButton)copy(copyButton);interactions(event)});
  $("#atlasModalClose").onclick=closeModal;$("#atlasBackdrop").onclick=closeModal;document.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal()});
})();
